run:
	@echo
	mvn -X -Pgraal clean package
	@echo
	@echo "Compare with"
	@echo
	@echo "  time java -jar target/graalvm-hellospring-cli-1.0.0.jar Miki Christoph"
	@echo
	@echo "  time target/hellospring-cli Miki Christoph"
	@echo
