run:
	@echo
	mvn -X -Pgraal clean package
	@echo
	@echo "Start with"
	@echo
	@echo "  PORT=8081 java -jar target/graalvm-hellospring-rest-1.0.0.jar"
	@echo
	@echo "  PORT=8082 target/hellospring-rest"
	@echo
